apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  - kustomizeConfig:
      overlays:
      - gu-custom
      parameters:
      - name: s3_endpoint_url
        value: s3.odh.com
      repoRef:
        name: manifests
        path: jupyterhub/jupyterhub
    name: jupyterhub
  - kustomizeConfig:
      overlays:
      - additional
      repoRef:
        name: manifests
        path: jupyterhub/notebook-images
    name: notebook-images
  repos:
  - name: kf-manifests
    uri: https://github.com/opendatahub-io/manifests/tarball/v1.0-branch-openshift
  - name: manifests
    uri: https://github.com/hlinander/odh-manifests/tarball/gu-fysik-lfy032
  version: v0.8.0
